# Generated by Django 4.2.7 on 2024-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0004_remove_badgeuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='badgeuser',
            name='validity_date',
            field=models.DateField(),
        ),
    ]
