# Generated by Django 4.2.7 on 2024-01-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_alter_badgeuser_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgeUser',
        ),
    ]
