# Generated by Django 4.2.7 on 2024-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('validity_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/')),
            ],
        ),
    ]
