# Generated by Django 5.0.1 on 2024-01-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_usereditrequest_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereditrequest',
            name='novoNome',
        ),
        migrations.AddField(
            model_name='usereditrequest',
            name='birth_date',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='usereditrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='usereditrequest',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usereditrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usereditrequest',
            name='picture',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
