# Generated by Django 4.2.7 on 2024-01-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_usereditrequest_novonome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
